# Generated by Django 3.1 on 2020-08-28 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_arrival', models.DateField(default=datetime.date(2020, 8, 29))),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('special_sign', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pets',
        ),
    ]
