# Generated by Django 3.1 on 2020-08-29 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_pet_deleted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_of_arrival',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 18, 53, 0, 324138, tzinfo=utc)),
        ),
    ]
