# Generated by Django 3.1 on 2020-08-29 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_auto_20200829_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_of_arrival',
            field=models.DateField(default=datetime.date(2020, 8, 29)),
        ),
    ]
