# Generated by Django 3.1 on 2020-08-29 20:56

import datetime
from django.db import migrations, models
import shelter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_auto_20200829_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_of_arrival',
            field=models.DateField(default=datetime.date.today, validators=[shelter.validators.validate_date_of_arrival]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='height_cm',
            field=models.FloatField(validators=[shelter.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight_kg',
            field=models.FloatField(validators=[shelter.validators.validate_positive]),
        ),
    ]
